apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    name: mongodb-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 172.28.42.75  # WSL2의 NFS 서버 IP 주소
    path: /home/bok/eduFocus/bok/save_saliency/saliency_contents
  storageClassName: mongodb-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      name: mongodb-pv
  storageClassName: mongodb-storage