apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-aggregator
  template:
    metadata:
      labels:
        app: result-aggregator
    spec:
      containers:
      - name: result-aggregator
        image: pepi10/aggr-test:latest
        env:
        - name: MINIO_ENDPOINT
          value: "minio-service:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secret-key
        - name: MINIO_SECURE
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: result-aggregator-service
spec:
  selector:
    app: result-aggregator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
