apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_PASSWORD
      ## pv.yaml 실행시 
      #   volumeMounts:
      #   - name: mongodb-storage
      #     mountPath: /data/db  # MongoDB의 기본 데이터 저장 경로
      # volumes:
      # - name: mongodb-storage
      #   persistentVolumeClaim:
      #     claimName: mongodb-pvc


---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb