apiVersion: apps/v1
kind: Deployment
metadata:
  name: saliency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saliency
  template:
    metadata:
      labels:
        app: saliency
    spec:
      containers:
      - name: saliency
        image: your_image_name  # Docker Hub 또는 다른 레지스트리에 업로드한 이미지
        ports:
        - containerPort: 80  # 필요한 경우 포트 수정
        env:
        - name: MONGODB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_USERNAME
        - name: MONGODB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_PASSWORD
        - name: MONGODB_HOST
          value: mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MONGODB_DB
        volumeMounts:
        - name: app-volume
          mountPath: /app
        - name: contents-volume
          mountPath: /app/contents
      volumes:
      - name: app-volume
        hostPath:
          path: /path/to/your/app  # 실제 애플리케이션 경로
      - name: contents-volume
        hostPath:
          path: /path/to/your/contents  # 실제 컨텐츠 경로

apiVersion: v1
kind: Service
metadata:
  name: saliency
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: saliency
