FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY gaze_tracking.py .
COPY model/model_x.pkl model/model_y.pkl ./model/

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "gaze_tracking:app"]
