---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session
  template:
    metadata:
      labels:
        app: session
    spec:
      containers:
      - name: session
        image: pepi10/centralized-session:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
spec:
  selector:
    app: session
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
