apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-container
    image: curlimages/curl
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]