apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        image: IMAGE_PLACE
        env:
        - name: KAFKA_SERVER
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "kid_face_video"
        - name: PORT
          value: "5000"
