FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY api_gw.py .

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "api_gw:app"]
