apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    name: mongodb-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 172.28.42.75  # WSL2의 NFS 서버 IP 주소
    path: /home/bok/eduFocus/bok/kubernetes/save_saliency/saliency_contents
  storageClassName: mongodb-storage