apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  labels:
    name: mongodb-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 172.24.97.194  # WSL2의 NFS 서버 IP 주소
    path: /home/fp/eduFocus/bok/kubernetes/save_saliency/saliency_contents
  storageClassName: mongodb-storage