apiVersion: v2
appVersion: 1.6.1
dependencies:
- alias: cert-manager
  condition: cert-manager.enabled
  name: cert-manager
  repository: ""
  version: 1.5.0
- condition: dex.enabled
  name: dex
  repository: ""
  version: 2.31.2
- condition: istio.enabled
  name: istio
  repository: ""
  version: 1.14.1
- name: knative-serving
  repository: ""
  version: 1.2.5
- condition: minio.enabled
  name: minio
  repository: ""
  version: "1.0"
description: 'The Kubeflow project is dedicated to making deployments of machine learning
  (ML) workflows on Kubernetes simple, portable and scalable. Our goal is not to recreate
  other services, but to provide a straightforward way to deploy best-of-breed open-source
  systems for ML to diverse infrastructures. Anywhere you are running Kubernetes,
  you should be able to run Kubeflow. '
home: https://github.com/alauda/kubeflow-chart
keywords:
- Kubeflow
- Kubernetes
- machine learning
- tensorflow
- pytorch
- XGBoost
kubeVersion: '>=1.20.0'
maintainers:
- email: typhoonzero1986@gmail.com
  name: typhoonzero
name: kubeflow
sources:
- https://github.com/alauda/kubeflow-chart
- https://github.com/kubeflow/manifests
type: application
version: 1.6.2
