apiVersion: v2
appVersion: "1.0"
description: MinIO
keywords:
- Minio
- storage
- S3
kubeVersion: '>=1.17.0'
maintainers:
- email: typhoonzero1986@gmail.com
  name: typhoonzero
name: minio
sources:
- https://github.com/alauda/kubeflow-chart
type: application
version: "1.0"
