---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-manage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-manage
    template:
      metadata:
        labels:
          app: session-manage
      spec:
        containers:
        - name: session-manage
          image: IMAGE
          ports:
          - containerPort: 5000
          env:
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: session-manage-service
spec:
  selector:
    app: session-manage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
