FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY experimental_model_k8s.py .
COPY experimental_model/new_gaze_model.pkl ./model/

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "experimental_model_k8s:app"]
