---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-management
spec:
  replicas: 2
  seletor:
    matchLabels:
      app: session-management
  template:
    metadata:
      labels:
        app: session-management
    spec:
      containers:
      - name: session-management
        image: IMAGE
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: session-management-service
spec:
  selector:
    app: session-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
